# increase the scrollback buffer to a higher limit than the default 2000 lines
set -g history-limit 9999999

# use proper terminal
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# easy config reloads (with diagnostic)
bind M-z send-keys -t. 'source $HOME/.zshrc' Enter
bind M-r source-file ~/.tmux.conf \; display '*** Reloaded tmux config.'

# split panes with | and -
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# quick pane-switching with ALT
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -d

# switch windows using Shift-arrow without prefix
bind -n S-Left previous-window
bind -n S-Right next-window

# begin window numbering at 1 instead of 0 
set -g base-index 1
set -g pane-base-index 1

# navigating through windows with page up/down
unbind Pagedown
unbind Pageup
bind-key Pagedown next-window
bind-key Pageup previous-window

# show tmux info in terminal title
set -g set-titles on

# copy mode and paste buffer with M-[ and M-]
unbind [
unbind ] 
bind -n M-[ copy-mode
bind -n M-] paste-buffer

# copy and paste between panes (vi-styled)
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# stylize status bar
#set -g status-justify left
#set -g status-left-length 16
set-option -g status-position top
#set-window-option -g status-style fg=black,bg=colour120
#set-window-option -g status-left "#H "
#set-window-option -g status-left-style fg=white,bg=colour240
#set-window-option -g status-right "#[bg=colour240] %Y-%b-%d %a %I:%M%P"
#set-window-option -g status-right-style fg=white,bg=colour240
#set-window-option -g window-status-format " #I:#W#F "
#set-window-option -g window-status-style fg=black,bg=colour120
#set-window-option -g window-status-current-format " #I:#W "
#set-window-option -g window-status-current-style fg=colour120,bg=black

# stylize message popup
#set -g message-style fg=black,bg=colour33
#set -g message-command-style fg=colour33,bg=black

# set window title
set -g set-titles on
set -g set-titles-string "#(whoami) #h #S:#I:#W #{session_alerts}"

##
## TPM
##

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'fabioluciano/tmux-powerkit'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Config: tmux-powerkit
set -g @powerkit_theme 'kiribyte'
set -g @powerkit_theme_variant 'dark'
set -g @powerkit_plugins 'hostname'
set -g @powerkit_session_icon 'auto'
set -g @powerkit_transparent 'true'
set -g @powerkit_separator_style 'normal'
set -g @powerkit_plugin_datetime_format '%Y-%m-%d %I:%M:%S %p'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
